services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "12355:8000"
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
